### ISSUE TITLE
Mouse pointer increasing and decreasing size

### ISSUE THREAD

**Issue by wglastonio** [hereafter/mouse-spotlight#2]
In my personal PC, after the upgrade to the version 2.0.20.0, my mouse pointer increases and decreases randomly.

**Comment by hereafter** [comment]
This feature is from mac os x,  "share to find cursor", it is right now trigger by shake mouse back and forth quickly (4 times)

If you find it out of control, could you please turn it off from this toggle

![image](https://user-images.githubusercontent.com/1483954/153544166-4faf6437-804c-49a3-b874-9e5add19e75c.png)


Please kindly update me if this helps

**Comment by wglastonio** [comment]
Hi, this is soved.
As a feedback, actually, I had to turn-off both "Wiggle Mouse" and "Magnify Cursor".
Thanks!
